#ID 不要重复 内容随意 不要包含 . 和空格
'001':
  #匹配物品显示名 可选 没有此项则不限物品显示名
  name: 'example'
  #匹配物品Lore 可选 没有此项则不限物品Lore
  lore:
    - 'example'
  #匹配物品类型 可选 没有此项则不限物品类型 (虽然name,lore,type都是可选的,但至少要提供一个)
  type: 'PAPER'
  #物品使用后执行的动作 一行一个动作 可选(虽然可选 但应该不会有人留空吧?使用物品后没有任何动作有啥用???)
  #可选的动作有: cmd,op,console,tell,chat,sound,broadcast,give-money,give-points 不指定默认为cmd
  action:
    #格式为 动作: 值
    #动作后面紧跟一个英文冒号 否则无法识别出正确动作会默认为是cmd动作
    #cmd = 让使用物品的玩家执行的命令 命令不需要加 /
    - 'cmd: help'
    #op = 让使用物品的玩家以op身份执行的命令 同样不需要加 /
    - 'op: list'
    #console = 让控制台执行的命令
    - 'console: say hi {player}'
    #tell = 给使用物品的玩家发送消息
    - 'tell: hi {player}'
    #chat = 让使用物品的玩家发送聊天消息
    - 'chat: 我使用了example'
    #sound = 给使用物品的玩家播放的音效
    - 'sound: ENTITY_EXPERIENCE_ORB_PICKUP'
    #broadcast = 给全服玩家发送的消息(公告)
    - 'broadcast: {player}使用了example'
    #give-money = 给予使用物品的玩家指定数量的钱 只能为正整数 使用此功能需要安装Vault以及支持Vault的经济插件
    - 'give-money: 10'
    #give-points = 给予使用物品的玩家指定数量的点券 只能为正整数 使用此功能需要安装PlayerPoints插件
    - 'give-points: 10'
  #使用物品需要花费的钱 可选 不能为负数
  price: 10
  #使用物品需要花费的点券 可选 不能为负数
  points: 10
  #使用物品需要花费的经验等级 可选 不能为负数
  levels: 10
  #使用物品需要的权限 可选
  permission: 'example'
  #使用物品会消耗的数量 可选 不能为负数 物品数量不足不能使用 提供0或没有此项则不消耗物品
  required-amount: 1
  #冷却时间 单位秒 可选 不能为负数 如果设置了冷却时间 表示使用物品后必须等待指定的时间后才能再次使用物品(冷却期间其他物品也不能使用)
  cooldown: 10

#一个简单的匹配物品显示名的例子：
'002':
  #注意 所有用到颜色符号的地方请使用 § 而不是 &
  name: '§6银票'
  action:
    - 'give-money: 100'
    - 'tell: §b你使用了一张§6银票§b, 获得了100银币.'
  required-amount: 1

#一个匹配物品显示名以及物品类型的例子：
'003':
  #注意 这里就不要再用 '§6银票' 这个名称了, 因为上面那个例子只要求物品名称一致 这里再用这个名称就完全符合上面那个例子的匹配条件了
  #name: '§6银票'
  name: '§6真·银票'
  #类型为纸
  type: 'PAPER'
  action:
    - 'give-money: 1000'
    - 'tell: §b你使用了一张§6真·银票§b, 获得了1000银币.'
  required-amount: 1
