name: ItemCommand
main: ml.mcos.itemcommand.ItemCommand
version: 1.0.0-SNAPSHOT
api-version: 1.13
author: myunco
softdepend:
  - Vault
  - PlayerPoints
  - PlaceholderAPI
commands:
  ItemCommand:
    usage: /ItemCommand <add|give|list|reload|version>
    aliases: ic
    permission: itemcommand.admin
permissions:
  itemcommand.admin:
    default: op
