name: ItemCommand
main: ml.mcos.itemcommand.ItemCommand
version: 1.0.0-BETA
api-version: 1.13
author: myunco
softdepend:
  - Vault
  - PlayerPoints
  - PlaceholderAPI
commands:
  itemcommand:
    usage: /ItemCommand <add|give|list|reload|version>
    aliases: ic
    permission: itemcommand.use
permissions:
  itemcommand.use:
    default: op
  itemcommand.admin:
    children:
      itemcommand.add: true
      itemcommand.give: true
      itemcommand.list: true
      itemcommand.reload: true
      itemcommand.version: true
    default: op
